import { expect, test } from '@playwright/test';
import type { GameAction, GameState } from '../src/game/content/contracts';
import { mergeBalanceConfig } from '../src/game/balance/config';
import { contentRegistry as content } from '../src/game/content/registry';
import { dispatchGameAction } from '../src/game/engine/actions';
import { calendarForDay } from '../src/game/engine/calendar';
import { createInitialState } from '../src/game/engine/initialState';
import { activityAtTime, defaultJobSchedule } from '../src/game/engine/schedule';
import { absoluteMinute } from '../src/game/engine/time';
import { awaitAppReady, bootWithBridge, navigate, openCareerPage, readCanonicalRecord, readPersistedState, writeCanonicalState } from './harness';

test.beforeEach(async ({ page }, testInfo) => {
  // The supported mobile product is landscape.
  await page.setViewportSize(testInfo.project.name === 'mobile' ? { width: 851, height: 393 } : { width: 1440, height: 1080 });
});

test('a unique qty2 cart is refused atomically; qty1 survives reload and coffee qty2 remains valid', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(String(error)));
  await bootWithBridge(page);
  await navigate(page, '商店');
  while (!await page.getByRole('button', { name: '加入购物袋：实用书籍', exact: true }).count()) await page.getByRole('button', { name: '下一页商品', exact: true }).click();
  const addBook = page.getByRole('button', { name: '加入购物袋：实用书籍', exact: true });
  const before = await page.evaluate(() => structuredClone(window.__yuliang!.store.getState().game));
  const savedBefore = await readCanonicalRecord(page);
  await addBook.click(); await addBook.click();
  await expect(page.getByRole('region', { name: '购物清单' })).toContainText('×2');
  await page.getByRole('button', { name: '一次购买', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('实用书籍暂时无法购买');
  expect(await page.evaluate(() => structuredClone(window.__yuliang!.store.getState().game))).toEqual(before);
  expect(await readCanonicalRecord(page)).toEqual(savedBefore);
  await page.getByRole('button', { name: '移除购物袋商品：实用书籍', exact: true }).click();
  await addBook.click(); await page.getByRole('button', { name: '一次购买', exact: true }).click();
  expect((await readPersistedState(page)).inventory).toMatchObject({ 'item.book-set': 1 });
  await page.reload(); await awaitAppReady(page);
  expect(await page.evaluate(() => window.__yuliang!.store.getState().game.inventory['item.book-set'])).toBe(1);
  await navigate(page, '商店');
  while (!await page.getByRole('button', { name: '加入购物袋：现磨咖啡', exact: true }).count()) await page.getByRole('button', { name: '下一页商品', exact: true }).click();
  const addCoffee = page.getByRole('button', { name: '加入购物袋：现磨咖啡', exact: true });
  await addCoffee.click(); await addCoffee.click(); await page.getByRole('button', { name: '一次购买', exact: true }).click();
  const saved = await readPersistedState(page);
  expect(saved.inventory).toMatchObject({ 'item.book-set': 1, 'item.seed-coffee': 2 });
  expect(saved.cash).toBe(344);
  expect(errors).toEqual([]);
});

for (const minuteOfDay of [16 * 60 + 40, 16 * 60 + 41, 17 * 60]) {
  test(`authored shorter-hours reward and gig UI at ${Math.floor(minuteOfDay / 60)}:${minuteOfDay % 60}`, async ({ page }) => {
    const balance = mergeBalanceConfig({ eventDailyLimit: 0, eventAmbientChance: 0 });
    const state = createInitialState(content, balance, 20);
    const job = content.jobs.find((entry) => entry.id === 'job.seed-warehouse')!;
    state.currentJobId = job.id;
    state.employment = { jobId: job.id, schedule: defaultJobSchedule(job), effectiveWeek: 1, startedDay: 1, basePay: job.basePay, salaryAdjustment: 0, negotiationStage: 0 };
    state.time = { day: 3, hour: Math.floor(minuteOfDay / 60), minute: minuteOfDay % 60 };
    state.calendar = calendarForDay(3);
    state.currentActivity = activityAtTime(state.time, state.weeklyPlan, state.employment, content, state);
    state.pendingEventId = 'event.salary-review';
    state.simulationMode = 'event';
    // A legal worker/event/clock fixture isolates the boundary. The reward is
    // chosen in the UI and the referral/Offer is generated by real engine calls.
    await bootWithBridge(page); await writeCanonicalState(page, state);
    await page.reload(); await awaitAppReady(page);
    await page.getByRole('button', { name: /希望时间更灵活/ }).click();
    await page.getByRole('button', { name: '收下并暂停', exact: true }).click();
    let offered = await page.evaluate(() => structuredClone(window.__yuliang!.store.getState().game)) as GameState;
    expect(offered.modifiers).toContainEqual({ target: 'work_hours', mode: 'multiply', value: 0.96, tags: ['work'] });
    for (const action of [
      { type: 'purchase_items', items: { 'item.seed-phone': 1 } },
      { type: 'start_storyline', storylineId: 'storyline.remote-connection' },
      { type: 'choose_storyline_branch', storylineId: 'storyline.remote-connection', branchId: 'meet' },
    ] as GameAction[]) {
      const result = dispatchGameAction(offered, action, content, balance);
      expect(result.error).toBeUndefined(); offered = result.state;
    }
    offered.rng.seed = 1;
    const opportunity = offered.opportunities!.find((entry) => entry.jobId === 'job.delivery-shift')!;
    const submitted = dispatchGameAction(offered, { type: 'submit_application', opportunityId: opportunity.id }, content, balance);
    expect(submitted.error).toBeUndefined();
    expect(submitted.state.applications!.some((entry) => entry.status === 'offer')).toBe(true);
    await writeCanonicalState(page, submitted.state); await page.reload(); await awaitAppReady(page);
    await navigate(page, '职业'); await openCareerPage(page, '我的申请');
    await page.getByRole('button', { name: '接受 Offer', exact: true }).click();
    if (minuteOfDay === 16 * 60 + 40) {
      await expect(page.getByRole('alert')).toContainText('班次与零工时间冲突');
      expect(await page.evaluate(() => window.__yuliang!.store.getState().game.applications![0].status)).toBe('offer');
      expect(await page.evaluate(() => window.__yuliang!.store.getState().game.gigs)).toEqual([]);
      return;
    }
    await openCareerPage(page, '工作机会');
    const gig = page.getByRole('heading', { name: '同城配送', exact: true }).locator('xpath=ancestor::article');
    await gig.getByRole('button', { name: '开始这段零工', exact: true }).click();
    await expect(gig.getByRole('button', { name: '继续这段零工', exact: true })).toBeVisible();
    const persisted = await readPersistedState(page) as unknown as GameState;
    expect(persisted.gigs![0].startedMinute).toBe(absoluteMinute(state.time));
    expect(persisted.time).toEqual(state.time);
    await page.reload(); await awaitAppReady(page);
    expect(await page.evaluate(() => window.__yuliang!.store.getState().game.gigs![0].startedMinute)).toBe(absoluteMinute(state.time));
  });
}
