import type { ActivityDefinition } from '../contracts';

export const officialActivities = [
  {
    id: 'activity.casual-meal',
    contentStatus: 'official',
    name: '随便吃点好的',
    description: '不用庆祝什么，也可以认真吃一顿。',
    tags: ['life', 'leisure'],
    category: 'food',
    financialCategory: 'food',
    locationId: 'location.central',
    options: [{ id: 'standard', label: '普通餐桌', durationMinutes: 60, cashCost: 45, effects: [{ type: 'attribute', attribute: 'mood', amount: 2 }] }],
  },
  {
    id: 'activity.cinema',
    contentStatus: 'official',
    name: '看电影',
    description: '两个小时不用想工作和收入。',
    tags: ['life', 'leisure'],
    category: 'film',
    financialCategory: 'entertainment',
    locationId: 'location.central',
    familiarityTags: ['film'],
    options: [
      { id: 'standard', label: '普通影厅', durationMinutes: 180, cashCost: 68, effects: [{ type: 'attribute', attribute: 'mood', amount: 5 }] },
      { id: 'premium', label: '特别放映', durationMinutes: 180, cashCost: 138, effects: [{ type: 'attribute', attribute: 'mood', amount: 7 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] },
      { id: 'with-zhou', label: '和周妍看一场', durationMinutes: 180, cashCost: 160, requiredCharacterId: 'character.seed-zhou', tags: ['social', 'film'], requirements: { type: 'relationship_at_least', characterId: 'character.seed-zhou', amount: 6 }, effects: [{ type: 'relation', characterId: 'character.seed-zhou', amount: 2 }, { type: 'attribute', attribute: 'mood', amount: 6 }] },
    ],
  },
  {
    id: 'activity.cafe-break',
    contentStatus: 'official',
    name: '去咖啡馆坐一会',
    description: '给自己留一小时，不为赚钱服务。',
    tags: ['life', 'social', 'leisure'],
    category: 'hobby',
    financialCategory: 'social',
    locationId: 'location.riverside',
    options: [
      { id: 'rest', label: '只是休息', durationMinutes: 60, cashCost: 38, effects: [{ type: 'attribute', attribute: 'mood', amount: 2 }] },
      { id: 'with-chenyu', label: '和陈宇坐坐', durationMinutes: 120, cashCost: 120, requiredCharacterId: 'character.chenyu', requirements: { type: 'relationship_at_least', characterId: 'character.chenyu', amount: 4 }, effects: [{ type: 'relation', characterId: 'character.chenyu', amount: 3 }, { type: 'attribute', attribute: 'mood', amount: 3 }] },
    ],
  },
  {
    id: 'activity.riverside-night-market',
    contentStatus: 'official',
    name: '河畔夜市',
    description: '沿着临江区的灯光走一圈，买一点小吃，也看看这座城市下班后的样子。',
    tags: ['life', 'social', 'leisure'],
    category: 'nightlife',
    financialCategory: 'entertainment',
    locationId: 'location.riverside',
    options: [{ id: 'market', label: '逛一圈', durationMinutes: 120, cashCost: 96, effects: [{ type: 'attribute', attribute: 'mood', amount: 4 }, { type: 'attribute', attribute: 'network', amount: 1 }] }],
  },
  {
    id: 'activity.industrial-design-exhibition',
    contentStatus: 'official',
    name: '北部产业设计展',
    description: '去北部产业区看一场设计展，理解一座城市如何把工作、制造和日常生活连在一起。',
    tags: ['life', 'travel', 'education'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.industrial',
    familiarityTags: ['design'],
    options: [{ id: 'exhibition', label: '看展', durationMinutes: 240, cashCost: 280, cooldownDays: 21, effects: [{ type: 'attribute', attribute: 'knowledge', amount: 2 }, { type: 'attribute', attribute: 'professional', amount: 1 }] }],
  },
  {
    id: 'activity.weekend-getaway',
    contentStatus: 'official',
    name: '周末短途旅行',
    description: '去临江区住一晚，把熟悉的生活暂时放到身后。',
    tags: ['life', 'travel', 'leisure'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.riverside',
    options: [
      { id: 'standard', label: '慢慢走走', durationMinutes: 240, cashCost: 360, cooldownDays: 14, effects: [{ type: 'attribute', attribute: 'mood', amount: 8 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] },
      { id: 'evening-walk', label: '临江夜游', durationMinutes: 240, cashCost: 520, cooldownDays: 14, effects: [{ type: 'attribute', attribute: 'mood', amount: 10 }, { type: 'attribute', attribute: 'network', amount: 1 }] },
    ],
  },
  {
    id: 'activity.old-town-culture',
    contentStatus: 'official',
    name: '旧城文化日',
    description: '去旧城文化区看展览、走走老街，不把每次出门都换算成收益。',
    tags: ['life', 'travel', 'leisure'],
    category: 'culture',
    financialCategory: 'travel',
    locationId: 'location.old-town',
    options: [{ id: 'exhibition', label: '看一场展览', durationMinutes: 240, cashCost: 220, effects: [] }],
  },
  {
    id: 'activity.browse-bookstore',
    contentStatus: 'official',
    name: '周末逛书店',
    description: '在旧城书店慢慢翻几本书，让兴趣和知识都留下一点余量。',
    tags: ['life', 'hobby', 'leisure'],
    category: 'hobby',
    financialCategory: 'entertainment',
    locationId: 'location.old-town',
    options: [{ id: 'browse', label: '随便逛逛', durationMinutes: 120, cashCost: 55, effects: [{ type: 'attribute', attribute: 'knowledge', amount: 1 }] }],
  },
  {
    id: 'activity.city-photography',
    contentStatus: 'official',
    name: '城市摄影练习',
    description: '带着相机走一圈，把兴趣变成可以继续发展的熟练度。',
    tags: ['life', 'hobby', 'photography'],
    category: 'culture',
    financialCategory: 'entertainment',
    locationId: 'location.central',
    familiarityTags: ['photography'],
    options: [{ id: 'walk', label: '街区取景', durationMinutes: 120, cashCost: 40, requirements: { type: 'owns_item', itemId: 'item.vintage-camera' }, effects: [{ type: 'attribute', attribute: 'knowledge', amount: 1 }] }],
  },
  {
    id: 'activity.brand-film-project',
    contentStatus: 'official',
    name: '品牌短片项目',
    description: '为已有企业接下一个明确的客户合同，把经营收入和项目成本分开看。',
    tags: ['business', 'project', 'career'],
    category: 'premium',
    financialCategory: 'business_income',
    locationId: 'location.riverside',
    options: [{ id: 'contract', label: '完成客户合同', durationMinutes: 240, cashCost: 0, requirements: { type: 'owns_business', businessId: 'business.service-studio' }, effects: [{ type: 'attribute', attribute: 'professional', amount: 2 }, { type: 'attribute', attribute: 'network', amount: 1 }], businessProject: { businessId: 'business.service-studio', revenue: 8000, cost: 3200 } }],
  },
] satisfies readonly ActivityDefinition[];
