import type { ActivityDefinition } from '../contracts';

export const officialActivities = [
  {
    id: 'activity.casual-meal',
    contentStatus: 'official',
    name: '随便吃点好的',
    description: '不用庆祝什么，也可以认真吃一顿。',
    tags: ['life', 'leisure'],
    category: 'food',
    financialCategory: 'food',
    locationId: 'location.central',
    options: [{ id: 'standard', label: '普通餐桌', durationMinutes: 60, cashCost: 45, effects: [{ type: 'attribute', attribute: 'mood', amount: 2 }] }],
  },
  {
    id: 'activity.cinema',
    contentStatus: 'official',
    name: '看电影',
    description: '两个小时不用想工作和收入。',
    tags: ['life', 'leisure'],
    category: 'film',
    financialCategory: 'entertainment',
    locationId: 'location.central',
    familiarityTags: ['film'],
    options: [
      { id: 'standard', label: '普通影厅', durationMinutes: 180, cashCost: 68, effects: [{ type: 'attribute', attribute: 'mood', amount: 5 }] },
      { id: 'premium', label: '特别放映', durationMinutes: 180, cashCost: 138, effects: [{ type: 'attribute', attribute: 'mood', amount: 7 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] },
      { id: 'with-zhou', label: '和周妍看一场', durationMinutes: 180, cashCost: 160, requiredCharacterId: 'character.seed-zhou', tags: ['social', 'film'], requirements: { type: 'relationship_at_least', characterId: 'character.seed-zhou', amount: 6 }, effects: [{ type: 'relation', characterId: 'character.seed-zhou', amount: 2 }, { type: 'attribute', attribute: 'mood', amount: 6 }] },
    ],
  },
  {
    id: 'activity.cafe-break',
    contentStatus: 'official',
    name: '去咖啡馆坐一会',
    description: '给自己留一小时，不为赚钱服务。',
    tags: ['life', 'social', 'leisure'],
    category: 'hobby',
    financialCategory: 'social',
    locationId: 'location.riverside',
    options: [
      { id: 'rest', label: '只是休息', durationMinutes: 60, cashCost: 38, effects: [{ type: 'attribute', attribute: 'mood', amount: 2 }] },
      { id: 'with-chenyu', label: '和陈宇坐坐', durationMinutes: 120, cashCost: 120, requiredCharacterId: 'character.chenyu', requirements: { type: 'relationship_at_least', characterId: 'character.chenyu', amount: 4 }, effects: [{ type: 'relation', characterId: 'character.chenyu', amount: 3 }, { type: 'attribute', attribute: 'mood', amount: 3 }] },
    ],
  },
  {
    id: 'activity.riverside-night-market',
    contentStatus: 'official',
    name: '河畔夜市',
    description: '沿着临江区的灯光走一圈，买一点小吃，也看看这座城市下班后的样子。',
    tags: ['life', 'social', 'leisure'],
    category: 'nightlife',
    financialCategory: 'entertainment',
    locationId: 'location.riverside',
    options: [{ id: 'market', label: '逛一圈', durationMinutes: 120, cashCost: 96, effects: [{ type: 'attribute', attribute: 'mood', amount: 4 }, { type: 'attribute', attribute: 'network', amount: 1 }] }],
  },
  {
    id: 'activity.industrial-design-exhibition',
    contentStatus: 'official',
    name: '北部产业设计展',
    description: '去北部产业区看一场设计展，理解一座城市如何把工作、制造和日常生活连在一起。',
    tags: ['life', 'travel', 'education'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.industrial',
    familiarityTags: ['design'],
    options: [{ id: 'exhibition', label: '看展', durationMinutes: 240, cashCost: 280, cooldownDays: 21, effects: [{ type: 'attribute', attribute: 'knowledge', amount: 2 }, { type: 'attribute', attribute: 'professional', amount: 1 }] }],
  },
  {
    id: 'activity.weekend-getaway',
    contentStatus: 'official',
    name: '周末短途旅行',
    description: '去临江区住一晚，把熟悉的生活暂时放到身后。',
    tags: ['life', 'travel', 'leisure'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.riverside',
    options: [
      { id: 'standard', label: '慢慢走走', durationMinutes: 240, cashCost: 360, cooldownDays: 14, effects: [{ type: 'attribute', attribute: 'mood', amount: 8 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] },
      { id: 'evening-walk', label: '临江夜游', durationMinutes: 240, cashCost: 520, cooldownDays: 14, effects: [{ type: 'attribute', attribute: 'mood', amount: 10 }, { type: 'attribute', attribute: 'network', amount: 1 }] },
    ],
  },
  {
    id: 'activity.old-town-culture',
    contentStatus: 'official',
    name: '旧城文化日',
    description: '去旧城文化区看展览、走走老街，不把每次出门都换算成收益。',
    tags: ['life', 'travel', 'leisure'],
    category: 'culture',
    financialCategory: 'travel',
    locationId: 'location.old-town',
    options: [{ id: 'exhibition', label: '看一场展览', durationMinutes: 240, cashCost: 220, effects: [] }],
  },
  {
    id: 'activity.riverside-park-ride',
    contentStatus: 'official',
    name: '临江公园骑行',
    description: '沿着临江区的公园慢慢骑一圈，把一段时间留给身体和风景。',
    tags: ['life', 'travel', 'hobby'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.riverside',
    familiarityTags: ['cycling'],
    options: [{ id: 'ride', label: '沿江骑行', durationMinutes: 180, cashCost: 180, cooldownDays: 21, effects: [{ type: 'attribute', attribute: 'fitness', amount: 2 }, { type: 'attribute', attribute: 'mood', amount: 4 }] }],
  },
  {
    id: 'activity.browse-bookstore',
    contentStatus: 'official',
    name: '周末逛书店',
    description: '在旧城书店慢慢翻几本书，让兴趣和知识都留下一点余量。',
    tags: ['life', 'hobby', 'leisure'],
    category: 'hobby',
    financialCategory: 'entertainment',
    locationId: 'location.old-town',
    options: [{ id: 'browse', label: '随便逛逛', durationMinutes: 120, cashCost: 55, effects: [{ type: 'attribute', attribute: 'knowledge', amount: 1 }] }, { id: 'with-zhou', label: '和周妍一起逛', durationMinutes: 120, cashCost: 110, requiredCharacterId: 'character.seed-zhou', tags: ['culture', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.seed-zhou', amount: 5 }, effects: [{ type: 'relation', characterId: 'character.seed-zhou', amount: 2 }, { type: 'attribute', attribute: 'knowledge', amount: 1 }] }, { id: 'with-lin', label: '和林晨一起逛', durationMinutes: 120, cashCost: 110, requiredCharacterId: 'character.seed-lin', tags: ['culture', 'hobby', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.seed-lin', amount: 5 }, effects: [{ type: 'relation', characterId: 'character.seed-lin', amount: 2 }, { type: 'attribute', attribute: 'knowledge', amount: 1 }] }],
  },
  {
    id: 'activity.city-photography',
    contentStatus: 'official',
    name: '城市摄影练习',
    description: '带着相机走一圈，把兴趣变成可以继续发展的熟练度。',
    tags: ['life', 'hobby', 'photography'],
    category: 'culture',
    financialCategory: 'entertainment',
    locationId: 'location.central',
    familiarityTags: ['photography'],
    options: [{ id: 'walk', label: '街区取景', durationMinutes: 120, cashCost: 40, requirements: { type: 'owns_item', itemId: 'item.vintage-camera' }, effects: [{ type: 'attribute', attribute: 'knowledge', amount: 1 }] }],
  },
  {
    id: 'activity.weekend-camping',
    contentStatus: 'official',
    name: '周末露营',
    description: '带上装备去临江区的开阔地过一晚，让生活暂时离开熟悉的室内节奏。',
    tags: ['life', 'travel', 'leisure'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.riverside',
    familiarityTags: ['travel'],
    options: [{ id: 'camp', label: '搭帐篷住一晚', durationMinutes: 240, cashCost: 260, cooldownDays: 28, requirements: { type: 'owns_item', itemId: 'item.camping-gear' }, effects: [{ type: 'attribute', attribute: 'fitness', amount: 2 }, { type: 'attribute', attribute: 'mood', amount: 7 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] }],
  },
  {
    id: 'activity.new-restaurant',
    contentStatus: 'official',
    name: '去一家新餐厅',
    description: '换一张菜单，也换一个观察这座城市的角度。',
    tags: ['life', 'leisure'],
    category: 'food',
    financialCategory: 'food',
    locationId: 'location.central',
    options: [{ id: 'dinner', label: '认真吃一顿', durationMinutes: 120, cashCost: 120, effects: [{ type: 'attribute', attribute: 'mood', amount: 4 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] }],
  },
  {
    id: 'activity.fine-dining',
    contentStatus: 'official',
    name: '精品餐厅晚餐',
    description: '把一次晚餐留给味道、谈话和不必匆忙的时间。',
    tags: ['life', 'leisure', 'social'],
    category: 'premium',
    financialCategory: 'food',
    locationId: 'location.central',
    options: [{ id: 'dinner', label: '慢慢吃完', durationMinutes: 180, cashCost: 380, effects: [{ type: 'attribute', attribute: 'mood', amount: 7 }, { type: 'attribute', attribute: 'appearance', amount: 1 }] }],
  },
  {
    id: 'activity.luxury-dining',
    contentStatus: 'official',
    name: '高端餐厅体验',
    description: '偶尔把生活品质放在账本之外，认真体验一顿饭。',
    tags: ['life', 'leisure', 'luxury'],
    category: 'premium',
    financialCategory: 'food',
    locationId: 'location.central',
    options: [{ id: 'tasting', label: '完整体验', durationMinutes: 180, cashCost: 880, effects: [{ type: 'attribute', attribute: 'mood', amount: 10 }, { type: 'stat', stat: 'lifestyle', amount: 2 }] }],
  },
  {
    id: 'activity.specialty-cafe',
    contentStatus: 'official',
    name: '精品咖啡馆',
    description: '坐两个小时，听见邻桌的城市，也给自己留一点空白。',
    tags: ['life', 'social', 'leisure'],
    category: 'hobby',
    financialCategory: 'social',
    locationId: 'location.riverside',
    options: [{ id: 'tasting', label: '慢慢喝一杯', durationMinutes: 120, cashCost: 68, effects: [{ type: 'attribute', attribute: 'mood', amount: 4 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] }],
  },
  {
    id: 'activity.home-gaming',
    contentStatus: 'official',
    name: '在家玩游戏',
    description: '不用出门，也可以把一段晚上交给纯粹的娱乐。',
    tags: ['life', 'leisure'],
    category: 'game',
    financialCategory: 'entertainment',
    locationId: 'location.old-town',
    options: [
      { id: 'one-hour', label: '玩一小时', durationMinutes: 60, cashCost: 0, requirements: { type: 'any', conditions: [{ type: 'owns_item', itemId: 'item.seed-laptop' }, { type: 'owns_item', itemId: 'item.tablet' }] }, effects: [{ type: 'attribute', attribute: 'mood', amount: 2 }] },
      { id: 'two-hours', label: '玩两小时', durationMinutes: 120, cashCost: 0, requirements: { type: 'any', conditions: [{ type: 'owns_item', itemId: 'item.seed-laptop' }, { type: 'owns_item', itemId: 'item.tablet' }] }, effects: [{ type: 'attribute', attribute: 'mood', amount: 4 }] },
    ],
  },
  {
    id: 'activity.concert',
    contentStatus: 'official',
    name: '演唱会',
    description: '在人群和音乐里度过一个完整的晚上，暂时不计算下一步。',
    tags: ['life', 'travel', 'leisure'],
    category: 'culture',
    financialCategory: 'entertainment',
    locationId: 'location.old-town',
    familiarityTags: ['music'],
    options: [{ id: 'show', label: '去现场', durationMinutes: 240, cashCost: 680, cooldownDays: 28, effects: [{ type: 'attribute', attribute: 'mood', amount: 12 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] }],
  },
  {
    id: 'activity.weekend-brunch',
    contentStatus: 'official',
    name: '周末早午餐',
    description: '把周末的上午交给一顿不必赶时间的饭。',
    tags: ['life', 'leisure'],
    category: 'food',
    financialCategory: 'food',
    locationId: 'location.riverside',
    options: [{ id: 'brunch', label: '慢慢吃一顿', durationMinutes: 120, cashCost: 160, effects: [{ type: 'attribute', attribute: 'mood', amount: 5 }] }],
  },
  {
    id: 'activity.late-night-food',
    contentStatus: 'official',
    name: '深夜宵夜',
    description: '一天还没有结束，先用一顿热食把自己照顾好。',
    tags: ['life', 'leisure'],
    category: 'food',
    financialCategory: 'food',
    locationId: 'location.old-town',
    options: [{ id: 'late-meal', label: '吃点热的', durationMinutes: 120, cashCost: 90, effects: [{ type: 'attribute', attribute: 'mood', amount: 4 }] }],
  },
  {
    id: 'activity.premium-cinema',
    contentStatus: 'official',
    name: 'IMAX 高规格电影',
    description: '偶尔把一部电影当作一次完整的现场体验。',
    tags: ['life', 'leisure'],
    category: 'film',
    financialCategory: 'entertainment',
    locationId: 'location.central',
    familiarityTags: ['film'],
    options: [{ id: 'imax', label: '特别放映厅', durationMinutes: 180, cashCost: 138, effects: [{ type: 'attribute', attribute: 'mood', amount: 7 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] }],
  },
  {
    id: 'activity.home-movie',
    contentStatus: 'official',
    name: '在家看电影',
    description: '不出门也能给晚上留一段完整的故事时间。',
    tags: ['life', 'leisure'],
    category: 'film',
    financialCategory: 'entertainment',
    locationId: 'location.old-town',
    familiarityTags: ['film'],
    options: [{ id: 'screening', label: '在家看一部', durationMinutes: 120, cashCost: 20, requirements: { type: 'any', conditions: [{ type: 'owns_item', itemId: 'item.seed-laptop' }, { type: 'owns_item', itemId: 'item.tablet' }] }, effects: [{ type: 'attribute', attribute: 'mood', amount: 4 }] }],
  },
  {
    id: 'activity.new-game-night',
    contentStatus: 'official',
    name: '买新游戏玩一晚',
    description: '本来只打算玩一会儿，抬头时已经过去几个小时。',
    tags: ['life', 'leisure'],
    category: 'game',
    financialCategory: 'entertainment',
    locationId: 'location.old-town',
    options: [{ id: 'play', label: '玩到尽兴', durationMinutes: 240, cashCost: 298, requirements: { type: 'any', conditions: [{ type: 'owns_item', itemId: 'item.seed-laptop' }, { type: 'owns_item', itemId: 'item.tablet' }] }, effects: [{ type: 'attribute', attribute: 'mood', amount: 9 }] }],
  },
  {
    id: 'activity.gym-session',
    contentStatus: 'official',
    name: '去健身房',
    description: '给身体安排一段明确的时间，也让心情重新获得一点秩序。',
    tags: ['life', 'hobby'],
    category: 'fitness',
    financialCategory: 'service',
    locationId: 'location.central',
    options: [
      { id: 'one-hour', label: '训练一小时', durationMinutes: 60, cashCost: 45, effects: [{ type: 'attribute', attribute: 'fitness', amount: 1 }, { type: 'attribute', attribute: 'mood', amount: 2 }] },
      { id: 'two-hours', label: '训练两小时', durationMinutes: 120, cashCost: 65, effects: [{ type: 'attribute', attribute: 'fitness', amount: 2 }, { type: 'attribute', attribute: 'mood', amount: 3 }] },
    ],
  },
  {
    id: 'activity.personal-training',
    contentStatus: 'official',
    name: '私教体验',
    description: '让一次训练更有针对性，也留意身体真正需要什么。',
    tags: ['life', 'hobby'],
    category: 'fitness',
    financialCategory: 'service',
    locationId: 'location.central',
    options: [{ id: 'session', label: '完成一次训练', durationMinutes: 120, cashCost: 380, cooldownDays: 7, effects: [{ type: 'attribute', attribute: 'fitness', amount: 4 }, { type: 'attribute', attribute: 'mood', amount: 3 }] }],
  },
  {
    id: 'activity.city-run',
    contentStatus: 'official',
    name: '城市跑步',
    description: '沿着熟悉的街区跑一圈，不为比赛，只为把身体带出门。',
    tags: ['life', 'hobby'],
    category: 'fitness',
    financialCategory: 'service',
    locationId: 'location.south-residential',
    options: [{ id: 'run', label: '跑一小时', durationMinutes: 60, cashCost: 0, effects: [{ type: 'attribute', attribute: 'fitness', amount: 1 }, { type: 'attribute', attribute: 'mood', amount: 1 }] }],
  },
  {
    id: 'activity.day-trip',
    contentStatus: 'official',
    name: '城郊一日游',
    description: '离开熟悉的几条街，给自己一天不被日程催促的时间。',
    tags: ['life', 'travel', 'leisure'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.riverside',
    familiarityTags: ['travel'],
    options: [{ id: 'day-out', label: '安排一日出行', durationMinutes: 240, cashCost: 280, cooldownDays: 30, effects: [{ type: 'attribute', attribute: 'mood', amount: 10 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] }],
  },
  {
    id: 'activity.premium-weekend',
    contentStatus: 'official',
    name: '品质周末旅行',
    description: '把周末过得从容一点，住得舒服，也走得慢一点。',
    tags: ['life', 'travel', 'leisure', 'luxury'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.riverside',
    familiarityTags: ['travel'],
    options: [{ id: 'premium-stay', label: '安排品质周末', durationMinutes: 2880, cashCost: 2200, cooldownDays: 60, effects: [{ type: 'attribute', attribute: 'mood', amount: 20 }, { type: 'stat', stat: 'lifestyle', amount: 3 }] }],
  },
  {
    id: 'activity.domestic-standard',
    contentStatus: 'official',
    name: '普通国内旅行',
    description: '去一座不熟悉的城市住几天，把视野从日常工作里抽出来。',
    tags: ['life', 'travel', 'leisure'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.old-town',
    familiarityTags: ['travel'],
    options: [{ id: 'explore', label: '安排国内探索', durationMinutes: 4320, cashCost: 2800, cooldownDays: 90, effects: [{ type: 'attribute', attribute: 'mood', amount: 24 }, { type: 'stat', stat: 'lifestyle', amount: 3 }] }],
  },
  {
    id: 'activity.luxury-vacation',
    contentStatus: 'official',
    name: '豪华度假',
    description: '有余量的时候，允许自己只考虑怎样舒服地生活。',
    tags: ['life', 'travel', 'leisure', 'luxury'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.old-town',
    familiarityTags: ['travel'],
    options: [{ id: 'resort', label: '安排豪华度假', durationMinutes: 7200, cashCost: 18000, cooldownDays: 120, effects: [{ type: 'attribute', attribute: 'mood', amount: 28 }, { type: 'stat', stat: 'lifestyle', amount: 7 }] }],
  },
  {
    id: 'activity.coffee-with-contact',
    contentStatus: 'official',
    name: '和联系人喝咖啡',
    description: '一杯咖啡的时间不长，但足够让一段关系从消息变成见面。',
    tags: ['life', 'social'],
    category: 'social',
    financialCategory: 'social',
    locationId: 'location.riverside',
    options: [
      { id: 'with-lin', label: '和林晨聊聊', durationMinutes: 120, cashCost: 100, requiredCharacterId: 'character.seed-lin', tags: ['culture', 'hobby', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.seed-lin', amount: 8 }, effects: [{ type: 'relation', characterId: 'character.seed-lin', amount: 3 }, { type: 'attribute', attribute: 'mood', amount: 3 }] },
      { id: 'with-xuke', label: '和徐可聊设备', durationMinutes: 120, cashCost: 100, requiredCharacterId: 'character.xuke', tags: ['technology', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.xuke', amount: 12 }, effects: [{ type: 'relation', characterId: 'character.xuke', amount: 3 }, { type: 'attribute', attribute: 'knowledge', amount: 1 }] },
      { id: 'with-guqing', label: '和顾清聊项目', durationMinutes: 120, cashCost: 120, requiredCharacterId: 'character.guqing', tags: ['culture', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.guqing', amount: 20 }, effects: [{ type: 'relation', characterId: 'character.guqing', amount: 4 }, { type: 'attribute', attribute: 'network', amount: 1 }] },
    ],
  },
  {
    id: 'activity.dinner-with-friend',
    contentStatus: 'official',
    name: '一起吃饭',
    description: '把工作和生活都放到餐桌上谈，关系也会有更具体的温度。',
    tags: ['life', 'social'],
    category: 'social',
    financialCategory: 'food',
    locationId: 'location.central',
    options: [
      { id: 'with-chenyu', label: '和陈宇吃饭', durationMinutes: 180, cashCost: 160, requiredCharacterId: 'character.chenyu', tags: ['meal', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.chenyu', amount: 0 }, effects: [{ type: 'relation', characterId: 'character.chenyu', amount: 4 }, { type: 'attribute', attribute: 'mood', amount: 4 }] },
      { id: 'with-zhou', label: '和周妍吃饭', durationMinutes: 180, cashCost: 160, requiredCharacterId: 'character.seed-zhou', tags: ['meal', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.seed-zhou', amount: 5 }, effects: [{ type: 'relation', characterId: 'character.seed-zhou', amount: 4 }, { type: 'attribute', attribute: 'mood', amount: 4 }] },
      { id: 'with-heyan', label: '和何彦聊房子', durationMinutes: 180, cashCost: 160, requiredCharacterId: 'character.heyan', tags: ['meal', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.heyan', amount: 10 }, effects: [{ type: 'relation', characterId: 'character.heyan', amount: 4 }, { type: 'attribute', attribute: 'network', amount: 1 }] },
    ],
  },
  {
    id: 'activity.exhibition-with-contact',
    contentStatus: 'official',
    name: '一起去看展',
    description: '在同一件作品前停下来，看看彼此关注的东西是否也有交集。',
    tags: ['life', 'hobby', 'social', 'leisure'],
    category: 'culture',
    financialCategory: 'entertainment',
    locationId: 'location.old-town',
    options: [
      { id: 'with-lin', label: '和林晨看展', durationMinutes: 180, cashCost: 160, requiredCharacterId: 'character.seed-lin', tags: ['culture', 'hobby', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.seed-lin', amount: 12 }, effects: [{ type: 'relation', characterId: 'character.seed-lin', amount: 4 }, { type: 'attribute', attribute: 'knowledge', amount: 1 }] },
      { id: 'with-guqing', label: '和顾清看展', durationMinutes: 180, cashCost: 160, requiredCharacterId: 'character.guqing', tags: ['culture', 'social'], requirements: { type: 'relationship_at_least', characterId: 'character.guqing', amount: 20 }, effects: [{ type: 'relation', characterId: 'character.guqing', amount: 4 }, { type: 'attribute', attribute: 'network', amount: 1 }] },
    ],
  },
  {
    id: 'activity.brand-film-project',
    contentStatus: 'official',
    name: '品牌短片项目',
    description: '为已有企业接下一个明确的客户合同，把经营收入和项目成本分开看。',
    tags: ['business', 'project', 'career'],
    category: 'premium',
    financialCategory: 'business_income',
    locationId: 'location.riverside',
    options: [{ id: 'contract', label: '完成客户合同', durationMinutes: 240, cashCost: 0, requirements: { type: 'owns_business', businessId: 'business.service-studio' }, effects: [{ type: 'attribute', attribute: 'professional', amount: 2 }, { type: 'attribute', attribute: 'network', amount: 1 }], businessProject: { businessId: 'business.service-studio', revenue: 8000, cost: 3200 } }],
  },
  {
    id: 'activity.riverside-stretch',
    contentStatus: 'official',
    name: '江堤拉伸晨练',
    description: '清晨的江堤没什么人，做一组拉伸，把一天的开始交给自己。',
    tags: ['life', 'hobby'],
    category: 'fitness',
    financialCategory: 'entertainment',
    locationId: 'location.south-residential',
    options: [{ id: 'morning', label: '完成一组拉伸', durationMinutes: 60, cashCost: 0, effects: [{ type: 'attribute', attribute: 'fitness', amount: 1 }, { type: 'attribute', attribute: 'mood', amount: 1 }] }],
  },
  {
    id: 'activity.park-open-class',
    contentStatus: 'official',
    name: '园区公开课',
    description: '科技园的开放讲座谁都能进，讲者水平随缘，收获看个人。',
    tags: ['life', 'career'],
    category: 'study',
    financialCategory: 'education',
    locationId: 'location.tech-park',
    options: [{ id: 'attend', label: '旁听一场分享', durationMinutes: 120, cashCost: 25, effects: [{ type: 'attribute', attribute: 'knowledge', amount: 1 }, { type: 'attribute', attribute: 'professional', amount: 1 }] }],
  },
] satisfies readonly ActivityDefinition[];
