import type { ActivityDefinition } from '../contracts';

export const officialActivities = [
  {
    id: 'activity.casual-meal',
    contentStatus: 'official',
    name: '随便吃点好的',
    description: '不用庆祝什么，也可以认真吃一顿。',
    tags: ['life', 'leisure'],
    category: 'food',
    financialCategory: 'food',
    locationId: 'location.central',
    options: [{ id: 'standard', label: '普通餐桌', durationMinutes: 60, cashCost: 45, effects: [{ type: 'attribute', attribute: 'mood', amount: 2 }] }],
  },
  {
    id: 'activity.cinema',
    contentStatus: 'official',
    name: '看电影',
    description: '两个小时不用想工作和收入。',
    tags: ['life', 'leisure'],
    category: 'film',
    financialCategory: 'entertainment',
    locationId: 'location.central',
    familiarityTags: ['film'],
    options: [
      { id: 'standard', label: '普通影厅', durationMinutes: 180, cashCost: 68, effects: [{ type: 'attribute', attribute: 'mood', amount: 5 }] },
      { id: 'premium', label: '特别放映', durationMinutes: 180, cashCost: 138, effects: [{ type: 'attribute', attribute: 'mood', amount: 7 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] },
    ],
  },
  {
    id: 'activity.cafe-break',
    contentStatus: 'official',
    name: '去咖啡馆坐一会',
    description: '给自己留一小时，不为赚钱服务。',
    tags: ['life', 'social', 'leisure'],
    category: 'hobby',
    financialCategory: 'social',
    locationId: 'location.riverside',
    options: [{ id: 'rest', label: '只是休息', durationMinutes: 60, cashCost: 38, effects: [{ type: 'attribute', attribute: 'mood', amount: 2 }] }],
  },
  {
    id: 'activity.weekend-getaway',
    contentStatus: 'official',
    name: '周末短途旅行',
    description: '去临江区住一晚，把熟悉的生活暂时放到身后。',
    tags: ['life', 'travel', 'leisure'],
    category: 'travel',
    financialCategory: 'travel',
    locationId: 'location.riverside',
    options: [{ id: 'standard', label: '慢慢走走', durationMinutes: 240, cashCost: 360, effects: [{ type: 'attribute', attribute: 'mood', amount: 8 }, { type: 'stat', stat: 'lifestyle', amount: 1 }] }],
  },
  {
    id: 'activity.brand-film-project',
    contentStatus: 'official',
    name: '品牌短片项目',
    description: '为已有企业接下一个明确的客户合同，把经营收入和项目成本分开看。',
    tags: ['business', 'project', 'career'],
    category: 'premium',
    financialCategory: 'business_income',
    locationId: 'location.riverside',
    options: [{ id: 'contract', label: '完成客户合同', durationMinutes: 240, cashCost: 0, requirements: { type: 'owns_business', businessId: 'business.service-studio' }, effects: [{ type: 'attribute', attribute: 'professional', amount: 2 }, { type: 'attribute', attribute: 'network', amount: 1 }], businessProject: { businessId: 'business.service-studio', revenue: 8000, cost: 3200 } }],
  },
] satisfies readonly ActivityDefinition[];
