import type { CompanyDefinition } from '../contracts';

export const officialCompanies: readonly CompanyDefinition[] = [
  { id: 'company.xinghe', contentStatus: 'official', name: '星河科技', description: '面向消费互联网的产品与运营团队。', tags: ['work', 'career'], industry: '互联网', locationId: 'location.central', jobIds: ['job.seed-office', 'job.operations-specialist', 'job.data-entry', 'job.category-operations-expert'] },
  { id: 'company.yuanwang', contentStatus: 'official', name: '远望零售', description: '覆盖线上与线下渠道的零售企业。', tags: ['work', 'career'], industry: '零售', locationId: 'location.riverside', jobIds: ['job.seed-office', 'job.customer-service', 'job.project-coordinator', 'job.regional-operations-manager'] },
  { id: 'company.qiming', contentStatus: 'official', name: '启明服务', description: '为本地客户提供运营与客户服务。', tags: ['work', 'career'], industry: '服务', locationId: 'location.industrial', jobIds: ['job.seed-shop-clerk', 'job.cafe-assistant', 'job.delivery-shift'], investmentIds: ['investment.qiming-equity'] },
  { id: 'company.huanliu', contentStatus: 'official', name: '环流物流', description: '连接仓储、调度与城市配送的物流运营团队。', tags: ['work', 'career', 'logistics'], industry: '物流', locationId: 'location.industrial', jobIds: ['job.huanliu-warehouse-assistant', 'job.huanliu-dispatch-coordinator'] },
  { id: 'company.greenfield-education', contentStatus: 'official', name: '青禾教育科技', description: '提供在线课程与职业培训服务的中型教育团队。', tags: ['work', 'career', 'education'], industry: '在线教育', locationId: 'location.central', jobIds: ['job.course-operations-assistant', 'job.learning-consultant', 'job.course-operations-specialist', 'job.course-teaching-assistant'] },
  { id: 'company.clearview-consulting', contentStatus: 'official', name: '澄明商业咨询', description: '为企业客户提供研究、分析与项目服务的商业咨询团队。', tags: ['work', 'career'], industry: '商业咨询', locationId: 'location.central', jobIds: ['job.research-assistant', 'job.business-analysis-assistant', 'job.business-analyst'] },
  { id: 'company.harbor-travel', contentStatus: 'official', name: '栖岸文旅', description: '连接旅行产品、酒店服务与城市周末体验的文旅运营团队。', tags: ['work', 'career'], industry: '旅游文旅', locationId: 'location.riverside', jobIds: ['job.travel-product-assistant'] },
  { id: 'company.starbridge-ecommerce', contentStatus: 'official', name: '星桥电商', description: '连接订单、商品与增长运营的电商团队。', tags: ['work', 'career'], industry: '电子商务', locationId: 'location.central', jobIds: ['job.order-operations-assistant', 'job.ecommerce-operations-assistant', 'job.ecommerce-operations-specialist', 'job.growth-operations'] },
  { id: 'company.neworder-auto', contentStatus: 'official', name: '新序汽车服务', description: '连接车辆销售、门店服务与客户运营的区域汽车服务企业。', tags: ['work', 'career'], industry: '汽车销售 / 汽车服务', locationId: 'location.riverside', jobIds: ['job.auto-service-assistant', 'job.sales-consultant-assistant', 'job.auto-sales-consultant', 'job.auto-customer-operations'] },
];
