import type { CompanyDefinition } from '../contracts';

export const officialCompanies: readonly CompanyDefinition[] = [
  { id: 'company.xinghe', contentStatus: 'official', name: '星河科技', description: '面向消费互联网的产品与运营团队。', tags: ['work', 'career'], industry: '互联网', locationId: 'location.central', history: [{ startYear: 1, title: '产品团队扩张' }, { startYear: 4, title: '推出企业服务线' }, { startYear: 4, title: '企业服务线并购整合', branchCondition: { type: 'flag', flag: 'xinghe_service_line_launched' } }, { startYear: 8, title: '进入成熟运营期' }], dynamicStates: [{ flag: 'xinghe_service_line_launched', title: '企业服务线提前启动（玩家参与）' }], jobIds: ['job.seed-office', 'job.operations-specialist', 'job.data-entry', 'job.category-operations-expert'] },
  { id: 'company.yuanwang', contentStatus: 'official', name: '远望零售', description: '覆盖线上与线下渠道的零售企业。', tags: ['work', 'career'], industry: '零售', locationId: 'location.riverside', history: [{ startYear: 1, title: '门店与社区零售' }, { startYear: 3, title: '进入电商渠道' }, { startYear: 7, title: '区域零售网络' }], jobIds: ['job.seed-office', 'job.customer-service', 'job.project-coordinator', 'job.regional-operations-manager'], investmentIds: ['investment.yuanwang-retail-equity'] },
  { id: 'company.qiming', contentStatus: 'official', name: '启明服务', description: '为本地客户提供运营与客户服务。', tags: ['work', 'career'], industry: '服务', locationId: 'location.industrial', history: [{ startYear: 1, title: '本地客户服务期' }, { startYear: 5, title: '标准化服务网络' }], jobIds: ['job.seed-shop-clerk', 'job.cafe-assistant', 'job.delivery-shift'], investmentIds: ['investment.qiming-equity'] },
  { id: 'company.huanliu', contentStatus: 'official', name: '环流物流', description: '连接仓储、调度与城市配送的物流运营团队。', tags: ['work', 'career', 'logistics'], industry: '物流', locationId: 'location.industrial', history: [{ startYear: 1, title: '仓储配送起步' }, { startYear: 4, title: '城市调度网络' }], jobIds: ['job.huanliu-warehouse-assistant', 'job.huanliu-dispatch-coordinator', 'job.city-dispatch-manager'] },
  { id: 'company.greenfield-education', contentStatus: 'official', name: '青禾教育科技', description: '提供在线课程与职业培训服务的中型教育团队。', tags: ['work', 'career', 'education'], industry: '在线教育', locationId: 'location.central', history: [{ startYear: 1, title: '在线课程起步' }, { startYear: 3, title: '职业培训线扩展' }, { startYear: 3, title: '北部转岗培训中心', branchCondition: { type: 'completed_event', eventId: 'event.industrial-hub-upgrade' } }], jobIds: ['job.course-operations-assistant', 'job.learning-consultant', 'job.course-operations-specialist', 'job.course-teaching-assistant', 'job.learning-product-lead'] },
  { id: 'company.clearview-consulting', contentStatus: 'official', name: '澄明商业咨询', description: '为企业客户提供研究、分析与项目服务的商业咨询团队。', tags: ['work', 'career'], industry: '商业咨询', locationId: 'location.central', history: [{ startYear: 1, title: '研究项目起步' }, { startYear: 4, title: '企业客户扩展' }], jobIds: ['job.research-assistant', 'job.business-analysis-assistant', 'job.business-analyst', 'job.principal-analyst'] },
  { id: 'company.harbor-travel', contentStatus: 'official', name: '栖岸文旅', description: '连接旅行产品、酒店服务与城市周末体验的文旅运营团队。', tags: ['work', 'career'], industry: '旅游文旅', locationId: 'location.riverside', history: [{ startYear: 1, title: '周末体验运营' }, { startYear: 5, title: '城市旅行产品线' }], jobIds: ['job.travel-product-assistant', 'job.travel-experience-designer'], investmentIds: ['investment.harbor-travel-equity'] },
  { id: 'company.starbridge-ecommerce', contentStatus: 'official', name: '星桥电商', description: '连接订单、商品与增长运营的电商团队。', tags: ['work', 'career'], industry: '电子商务', locationId: 'location.central', history: [{ startYear: 1, title: '订单运营团队成立' }, { startYear: 3, title: '增长业务独立' }, { startYear: 6, title: '区域平台化运营' }], jobIds: ['job.order-operations-assistant', 'job.ecommerce-operations-assistant', 'job.ecommerce-operations-specialist', 'job.growth-operations', 'job.starbridge-growth-director'], investmentIds: ['investment.starbridge-ecommerce-equity'] },
  { id: 'company.neworder-auto', contentStatus: 'official', name: '新序汽车服务', description: '连接车辆销售、门店服务与客户运营的区域汽车服务企业。', tags: ['work', 'career'], industry: '汽车销售 / 汽车服务', locationId: 'location.riverside', history: [{ startYear: 1, title: '区域门店服务' }, { startYear: 4, title: '客户运营体系' }], jobIds: ['job.auto-service-assistant', 'job.sales-consultant-assistant', 'job.auto-sales-consultant', 'job.auto-customer-operations', 'job.auto-regional-trainer'] },
  { id: 'company.frame-media', contentStatus: 'official', name: '映界传媒', description: '连接内容、广告、摄影与商业媒体的中型内容团队。', tags: ['work', 'career'], industry: '视频 / 内容 / 商业媒体', locationId: 'location.old-town', history: [{ startYear: 1, title: '内容制作起步' }, { startYear: 4, title: '商业媒体扩展' }], jobIds: ['job.production-assistant', 'job.content-editor', 'job.video-operations', 'job.media-producer-lead'] },
  { id: 'company.isle-lifestyle', contentStatus: 'official', name: '一屿生活科技', description: '连接智能家居、消费科技、产品与用户体验的成长型团队。', tags: ['work', 'career', 'technology'], industry: '智能家居 / 消费科技', locationId: 'location.central', history: [{ startYear: 1, title: '智能家居产品起步' }, { startYear: 5, title: '用户体验团队扩展' }], jobIds: ['job.customer-experience-assistant', 'job.product-support-specialist', 'job.user-research-assistant', 'job.lifestyle-product-operations', 'job.lifestyle-product-expert'], investmentIds: ['investment.isle-lifestyle-equity'] },
];
