import type { CourseDefinition } from '../contracts';

export const officialCourses = [
  {
    id: 'course.workplace-basics',
    contentStatus: 'official',
    name: '职场基础课',
    description: '把沟通、记录和按时交付练成一套可复用的工作习惯。',
    tags: ['education', 'career'],
    durationMinutes: 120,
    cashCost: 180,
    experienceTags: ['office', 'operations'],
    experienceGain: 2,
    qualificationId: 'qualification.workplace-basics',
    cooldownDays: 7,
    maxCompletions: 1,
    effects: [{ type: 'attribute', attribute: 'professional', amount: 2 }],
  },
  {
    id: 'course.office-tools',
    contentStatus: 'official',
    name: '办公室工具训练',
    description: '练习表格、资料整理与清晰汇报，适合准备进入办公室岗位。',
    tags: ['education', 'office'],
    durationMinutes: 180,
    cashCost: 320,
    experienceTags: ['office', 'data'],
    experienceGain: 3,
    qualificationId: 'qualification.office-tools',
    cooldownDays: 10,
    maxCompletions: 1,
    effects: [{ type: 'attribute', attribute: 'knowledge', amount: 3 }],
  },
  {
    id: 'course.data-analysis-basics',
    contentStatus: 'official',
    name: '数据分析入门',
    description: '从清理数据和寻找规律开始，为技术与分析方向积累一小步。',
    tags: ['education', 'data'],
    durationMinutes: 240,
    cashCost: 560,
    experienceTags: ['data', 'finance'],
    experienceGain: 4,
    qualificationId: 'qualification.data-analysis-basics',
    cooldownDays: 14,
    maxCompletions: 1,
    requirements: { type: 'attribute_at_least', attribute: 'knowledge', amount: 10 },
    effects: [{ type: 'attribute', attribute: 'knowledge', amount: 4 }],
  },
  {
    id: 'course.people-management',
    contentStatus: 'official',
    name: '团队管理基础',
    description: '从分工、反馈和协作开始，准备第一次真正带人。',
    tags: ['education', 'management', 'career'],
    durationMinutes: 240,
    cashCost: 2800,
    effects: [
      { type: 'attribute', attribute: 'communication', amount: 4 },
      { type: 'attribute', attribute: 'professional', amount: 2 },
    ],
    experienceTags: ['management'],
    experienceGain: 2,
    qualificationId: 'people_management_basics',
    cooldownDays: 30,
    maxCompletions: 1,
    requirements: {
      type: 'all',
      conditions: [
        { type: 'attribute_at_least', attribute: 'communication', amount: 30 },
        { type: 'attribute_at_least', attribute: 'professional', amount: 30 },
      ],
    },
  },
] satisfies readonly CourseDefinition[];
