import type { InvestmentDefinition } from '../contracts';

export const officialInvestments = [
  {
    id: 'investment.flexible-savings',
    contentStatus: 'official',
    name: '灵活储蓄',
    description: '波动很小、随时可以取用的现金替代品。',
    tags: ['investment', 'low-risk'],
    kind: 'savings',
    risk: 'low',
    baseValue: 100,
    minimumUnits: 1,
    dailyDrift: 0.00015,
    dailyVolatility: 0.0003,
    dividendRate: 0.00001,
  },
  {
    id: 'investment.fixed-deposit-3m',
    contentStatus: 'official',
    name: '三个月定期储蓄',
    description: '锁定三个月、收益略高的储蓄安排；提前取出只损失部分未结算利息。',
    tags: ['investment', 'low-risk'],
    kind: 'savings',
    risk: 'low',
    baseValue: 100,
    minimumUnits: 10,
    dailyDrift: 0.00008,
    dailyVolatility: 0.00012,
    dividendRate: 0.000025,
  },
  {
    id: 'investment.stable-money-market',
    contentStatus: 'official',
    name: '安稳货币基金',
    description: '几乎像现金一样易于理解的低波动工具，适合不想让现金完全闲置。',
    tags: ['investment', 'low-risk'],
    kind: 'fund',
    risk: 'low',
    baseValue: 1,
    minimumUnits: 100,
    dailyDrift: 0.00012,
    dailyVolatility: 0.00008,
    dividendRate: 0.000012,
  },
  {
    id: 'investment.city-bond-fund',
    contentStatus: 'official',
    name: '城市债券基金',
    description: '波动低、分红稳定的债券组合，收益不快，但不需要每天盯着价格。',
    tags: ['investment', 'low-risk'],
    kind: 'fund',
    risk: 'low',
    baseValue: 102.3,
    minimumUnits: 5,
    dailyDrift: 0.0002,
    dailyVolatility: 0.0007,
    dividendRate: 0.000055,
  },
  {
    id: 'investment.broad-market-index',
    contentStatus: 'official',
    name: '广域市场指数基金',
    description: '分散持有多个行业，适合长期配置。',
    tags: ['investment', 'low-risk', 'growth'],
    kind: 'fund',
    risk: 'low',
    baseValue: 108,
    minimumUnits: 1,
    dailyDrift: 0.00035,
    dailyVolatility: 0.0025,
    dividendRate: 0.00004,
  },
  {
    id: 'investment.technology-growth',
    contentStatus: 'official',
    name: '科技成长基金',
    description: '波动更高，也更接近技术和成长机会。',
    tags: ['investment', 'growth', 'technology'],
    kind: 'fund',
    risk: 'high',
    baseValue: 132,
    minimumUnits: 1,
    dailyDrift: 0.0007,
    dailyVolatility: 0.007,
    dividendRate: 0.00002,
  },
  {
    id: 'investment.growth-index',
    contentStatus: 'official',
    name: '成长企业指数基金',
    description: '配置科技、消费与新兴公司的中风险指数，长期潜力更高，短期回撤也更明显。',
    tags: ['investment', 'growth'],
    kind: 'fund',
    risk: 'medium',
    baseValue: 88,
    minimumUnits: 1,
    dailyDrift: 0.0005,
    dailyVolatility: 0.0045,
    dividendRate: 0.000025,
  },
  {
    id: 'investment.consumer-retail-fund',
    contentStatus: 'official',
    name: '消费与零售基金',
    description: '覆盖零售、电商与汽车服务，消费旺季可能带来变化，但比单一成长股更分散。',
    tags: ['investment', 'shopping'],
    kind: 'fund',
    risk: 'medium',
    baseValue: 76,
    minimumUnits: 1,
    dailyDrift: 0.00042,
    dailyVolatility: 0.0038,
    dividendRate: 0.000045,
  },
  {
    id: 'investment.travel-leisure-fund',
    contentStatus: 'official',
    name: '文旅消费基金',
    description: '连接旅行、酒店与娱乐消费的行业基金，适合观察城市生活扩张带来的长期机会。',
    tags: ['investment', 'travel', 'leisure'],
    kind: 'fund',
    risk: 'medium',
    baseValue: 64,
    minimumUnits: 1,
    dailyDrift: 0.0004,
    dailyVolatility: 0.0042,
    dividendRate: 0.000035,
  },
  {
    id: 'investment.gold-account',
    contentStatus: 'official',
    name: '实物黄金账户',
    description: '不分红、波动较低的保值型资产；它不会开会，只是让一部分现金换个形态。',
    tags: ['investment', 'asset'],
    kind: 'gold',
    risk: 'low',
    baseValue: 500,
    minimumUnits: 1,
    dailyDrift: 0.00025,
    dailyVolatility: 0.002,
  },
  {
    id: 'investment.commercial-reit',
    contentStatus: 'official',
    name: '商业地产 REIT',
    description: '持有一篮子商业物业份额，收益来自租金与估值变化。',
    tags: ['investment', 'asset'],
    kind: 'reit',
    risk: 'medium',
    baseValue: 118,
    minimumUnits: 1,
    dailyDrift: 0.00045,
    dailyVolatility: 0.004,
    dividendRate: 0.00008,
  },
  {
    id: 'investment.residential-reit',
    contentStatus: 'official',
    name: '租赁住宅 REIT',
    description: '持有一篮子租赁住宅份额，分红稳定，不需要玩家亲自管理整套房产。',
    tags: ['investment', 'asset', 'housing'],
    kind: 'reit',
    risk: 'low',
    baseValue: 84,
    minimumUnits: 1,
    dailyDrift: 0.00032,
    dailyVolatility: 0.0028,
    dividendRate: 0.000075,
  },
  {
    id: 'investment.matrix-cloud-equity',
    contentStatus: 'official',
    name: '矩阵云科技公开股权',
    description: '企业软件与云服务公司的成长型股权，收益主要来自估值变化，分红较低。',
    tags: ['investment', 'technology'],
    kind: 'stock',
    risk: 'high',
    baseValue: 38.6,
    minimumUnits: 1,
    dailyDrift: 0.00065,
    dailyVolatility: 0.006,
    dividendRate: 0.00001,
  },
  {
    id: 'investment.yuanwang-retail-equity',
    contentStatus: 'official',
    name: '远望零售集团公开股权',
    description: '线上线下零售企业的公开股权，业务相对稳定并有小额分红。',
    tags: ['investment', 'shopping'],
    kind: 'stock',
    risk: 'medium',
    baseValue: 26.8,
    minimumUnits: 1,
    dailyDrift: 0.00035,
    dailyVolatility: 0.0035,
    dividendRate: 0.00006,
    companyId: 'company.yuanwang',
  },
  {
    id: 'investment.starbridge-ecommerce-equity',
    contentStatus: 'official',
    name: '星桥电商公开股权',
    description: '订单与增长业务驱动的电商股权，波动高于传统零售，分红较少。',
    tags: ['investment', 'growth'],
    kind: 'stock',
    risk: 'high',
    baseValue: 44.2,
    minimumUnits: 1,
    dailyDrift: 0.00055,
    dailyVolatility: 0.0055,
    dividendRate: 0.000018,
    companyId: 'company.starbridge-ecommerce',
  },
  {
    id: 'investment.isle-lifestyle-equity',
    contentStatus: 'official',
    name: '一屿生活科技公开股权',
    description: '年轻而不稳定的消费科技股权，成长空间较大，但每日波动仍受限。',
    tags: ['investment', 'technology', 'growth'],
    kind: 'stock',
    risk: 'high',
    baseValue: 21.5,
    minimumUnits: 1,
    dailyDrift: 0.0007,
    dailyVolatility: 0.0065,
    dividendRate: 0.000012,
    companyId: 'company.isle-lifestyle',
  },
  {
    id: 'investment.luhai-manufacturing-equity',
    contentStatus: 'official',
    name: '陆海智造公开股权',
    description: '制造业企业股权，估值相对稳定，供应链与产能变化会带来有限波动。',
    tags: ['investment', 'asset'],
    kind: 'stock',
    risk: 'medium',
    baseValue: 31.4,
    minimumUnits: 1,
    dailyDrift: 0.00032,
    dailyVolatility: 0.0032,
    dividendRate: 0.00005,
  },
  {
    id: 'investment.harbor-travel-equity',
    contentStatus: 'official',
    name: '栖岸文旅公开股权',
    description: '与旅行、酒店和周末体验相关的文旅股权，偶尔分红，波动高于零售。',
    tags: ['investment', 'travel'],
    kind: 'stock',
    risk: 'high',
    baseValue: 18.8,
    minimumUnits: 1,
    dailyDrift: 0.00045,
    dailyVolatility: 0.0048,
    dividendRate: 0.00003,
    companyId: 'company.harbor-travel',
  },
  {
    id: 'investment.local-restaurant-share',
    contentStatus: 'official',
    name: '小型餐饮项目合伙份额',
    description: '由熟人引荐的本地餐饮项目份额，可能产生利润分成，但退出需要等待项目阶段。',
    tags: ['investment', 'business', 'private-equity', 'story'],
    kind: 'private_equity',
    risk: 'high',
    baseValue: 5_000,
    minimumUnits: 1,
    dailyDrift: 0.00055,
    dailyVolatility: 0.008,
    dividendRate: 0.00018,
    requirements: { type: 'flag', flag: 'local_restaurant_access' },
  },
  {
    id: 'investment.creative-studio-share',
    contentStatus: 'official',
    name: '独立工作室投资份额',
    description: '映界传媒圈子的早期创意项目份额，周期收益有限，也可能带来独家项目机会。',
    tags: ['investment', 'business', 'private-equity', 'story'],
    kind: 'private_equity',
    risk: 'high',
    baseValue: 15_000,
    minimumUnits: 1,
    dailyDrift: 0.00065,
    dailyVolatility: 0.009,
    dividendRate: 0.0002,
    requirements: { type: 'flag', flag: 'creative_studio_access' },
  },
  {
    id: 'investment.qiming-equity',
    contentStatus: 'official',
    name: '启明服务公开股权',
    description: '独立于自营企业的公开股权资产，收益来自估值变化与小额分红。',
    tags: ['investment', 'growth'],
    kind: 'company_equity',
    risk: 'medium',
    baseValue: 220,
    minimumUnits: 1,
    dailyDrift: 0.0004,
    dailyVolatility: 0.004,
    dividendRate: 0.00006,
    companyId: 'company.qiming',
  },
  {
    id: 'investment.citylife-private-equity',
    contentStatus: 'official',
    name: '城际生活早期股权',
    description: '不在公开市场挂牌的早期项目份额，只能通过人物与特殊机会获得。',
    tags: ['investment', 'private-equity', 'story'],
    kind: 'private_equity',
    risk: 'high',
    baseValue: 10_000,
    minimumUnits: 1,
    dailyDrift: 0.0008,
    dailyVolatility: 0.012,
    dividendRate: 0.00035,
    requirements: {
      type: 'flag',
      flag: 'private_equity_access',
    },
  },
] satisfies readonly InvestmentDefinition[];
