import type { InvestmentDefinition } from '../contracts';

export const officialInvestments = [
  {
    id: 'investment.flexible-savings',
    contentStatus: 'official',
    name: '灵活储蓄',
    description: '波动很小、随时可以取用的现金替代品。',
    tags: ['investment', 'low-risk'],
    kind: 'savings',
    risk: 'low',
    baseValue: 100,
    minimumUnits: 1,
    dailyDrift: 0.00015,
    dailyVolatility: 0.0003,
    dividendRate: 0.00001,
  },
  {
    id: 'investment.broad-market-index',
    contentStatus: 'official',
    name: '广域市场指数基金',
    description: '分散持有多个行业，适合长期配置。',
    tags: ['investment', 'low-risk', 'growth'],
    kind: 'fund',
    risk: 'low',
    baseValue: 108,
    minimumUnits: 1,
    dailyDrift: 0.00035,
    dailyVolatility: 0.0025,
    dividendRate: 0.00004,
  },
  {
    id: 'investment.technology-growth',
    contentStatus: 'official',
    name: '科技成长基金',
    description: '波动更高，也更接近技术和成长机会。',
    tags: ['investment', 'growth', 'technology'],
    kind: 'fund',
    risk: 'high',
    baseValue: 132,
    minimumUnits: 1,
    dailyDrift: 0.0007,
    dailyVolatility: 0.007,
    dividendRate: 0.00002,
  },
  {
    id: 'investment.commercial-reit',
    contentStatus: 'official',
    name: '商业地产 REIT',
    description: '持有一篮子商业物业份额，收益来自租金与估值变化。',
    tags: ['investment', 'asset'],
    kind: 'reit',
    risk: 'medium',
    baseValue: 118,
    minimumUnits: 1,
    dailyDrift: 0.00045,
    dailyVolatility: 0.004,
    dividendRate: 0.00008,
  },
] satisfies readonly InvestmentDefinition[];
