import type { InvestmentDefinition } from '../contracts';

export const officialInvestments = [
  {
    id: 'investment.flexible-savings',
    contentStatus: 'official',
    name: '灵活储蓄',
    description: '波动很小、随时可以取用的现金替代品。',
    tags: ['investment', 'low-risk'],
    kind: 'savings',
    risk: 'low',
    baseValue: 100,
    minimumUnits: 1,
    dailyDrift: 0.00015,
    dailyVolatility: 0.0003,
    dividendRate: 0.00001,
  },
  {
    id: 'investment.broad-market-index',
    contentStatus: 'official',
    name: '广域市场指数基金',
    description: '分散持有多个行业，适合长期配置。',
    tags: ['investment', 'low-risk', 'growth'],
    kind: 'fund',
    risk: 'low',
    baseValue: 108,
    minimumUnits: 1,
    dailyDrift: 0.00035,
    dailyVolatility: 0.0025,
    dividendRate: 0.00004,
  },
  {
    id: 'investment.technology-growth',
    contentStatus: 'official',
    name: '科技成长基金',
    description: '波动更高，也更接近技术和成长机会。',
    tags: ['investment', 'growth', 'technology'],
    kind: 'fund',
    risk: 'high',
    baseValue: 132,
    minimumUnits: 1,
    dailyDrift: 0.0007,
    dailyVolatility: 0.007,
    dividendRate: 0.00002,
  },
  {
    id: 'investment.commercial-reit',
    contentStatus: 'official',
    name: '商业地产 REIT',
    description: '持有一篮子商业物业份额，收益来自租金与估值变化。',
    tags: ['investment', 'asset'],
    kind: 'reit',
    risk: 'medium',
    baseValue: 118,
    minimumUnits: 1,
    dailyDrift: 0.00045,
    dailyVolatility: 0.004,
    dividendRate: 0.00008,
  },
  {
    id: 'investment.qiming-equity',
    contentStatus: 'official',
    name: '启明服务公开股权',
    description: '独立于自营企业的公开股权资产，收益来自估值变化与小额分红。',
    tags: ['investment', 'growth'],
    kind: 'company_equity',
    risk: 'medium',
    baseValue: 220,
    minimumUnits: 1,
    dailyDrift: 0.0004,
    dailyVolatility: 0.004,
    dividendRate: 0.00006,
    companyId: 'company.qiming',
  },
  {
    id: 'investment.citylife-private-equity',
    contentStatus: 'official',
    name: '城际生活早期股权',
    description: '不在公开市场挂牌的早期项目份额，只能通过人物与特殊机会获得。',
    tags: ['investment', 'private-equity', 'story'],
    kind: 'private_equity',
    risk: 'high',
    baseValue: 10_000,
    minimumUnits: 1,
    dailyDrift: 0.0008,
    dailyVolatility: 0.012,
    dividendRate: 0.00035,
    requirements: {
      type: 'flag',
      flag: 'private_equity_access',
    },
  },
] satisfies readonly InvestmentDefinition[];
