import type { JobDefinition } from '../contracts';

export const officialJobs = [
  {
    "id": "job.seed-shop-clerk",
    "contentStatus": "official",
    "name": "便利店店员",
    "description": "稳定的入门工作，收入普通，但几乎没有门槛。",
    "tags": [
      "work",
      "starter"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 8,
    "basePay": 96,
    "careerXp": 1,
    "experienceTags": ["retail", "customer_service"],
    "isLongTerm": true
  },
  {
    "id": "job.seed-warehouse",
    "contentStatus": "official",
    "name": "仓库理货员",
    "description": "按清单整理货物，收入比基础服务岗更高。",
    "tags": [
      "work",
      "starter"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 8,
    "basePay": 128,
    "abilityRequired": 10,
    "careerXp": 2,
    "experienceTags": ["logistics"],
    "isLongTerm": true
  },
  {
    "id": "job.delivery-shift",
    "contentStatus": "official",
    "name": "同城配送",
    "description": "四小时一班的临时配送，适合补一笔当天收入。",
    "tags": [
      "work",
      "starter"
    ],
    "kind": "temporary",
    "employmentKind": "gig",
    "hours": 4,
    "basePay": 76,
    "abilityRequired": 10,
    "careerXp": 1,
    "isLongTerm": false
  },
  {
    "id": "job.cafe-assistant",
    "contentStatus": "official",
    "name": "咖啡店店员",
    "description": "工时较短，收入稳定，也更容易积累声誉。",
    "tags": [
      "work",
      "starter"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 6,
    "basePay": 108,
    "abilityRequired": 11,
    "reputationRequired": 1,
    "careerXp": 2,
    "experienceTags": ["customer_service"],
    "rewards": [
      {
        "type": "stat",
        "stat": "reputation",
        "amount": 1
      }
    ],
    "isLongTerm": true
  },
  {
    "id": "job.seed-office",
    "contentStatus": "official",
    "name": "行政助理",
    "description": "处理日程、表格和日常沟通，是进入办公室工作的第一步。",
    "tags": [
      "work",
      "office",
      "career"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 168,
    "abilityRequired": 14,
    "reputationRequired": 3,
    "careerXp": 3,
    "experienceTags": ["office", "operations"],
    "isLongTerm": true
  },
  {
    "id": "job.customer-service",
    "contentStatus": "official",
    "name": "客户服务专员",
    "description": "处理咨询和售后，稳定积累职业经验与声誉。",
    "tags": [
      "work",
      "office",
      "career"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 196,
    "abilityRequired": 16,
    "reputationRequired": 6,
    "careerXp": 3,
    "experienceTags": ["customer_service"],
    "rewards": [
      {
        "type": "stat",
        "stat": "reputation",
        "amount": 1
      }
    ],
    "isLongTerm": true
  },
  {
    "id": "job.data-entry",
    "contentStatus": "official",
    "name": "数据整理兼职",
    "description": "在电脑上整理资料，时间灵活，适合与主业搭配。",
    "tags": [
      "work",
      "remote"
    ],
    "kind": "freelance",
    "employmentKind": "repeatable_side_job",
    "hours": 4,
    "basePay": 132,
    "abilityRequired": 15,
    "careerXp": 2,
    "requiredItems": [
      "item.seed-laptop"
    ],
    "requiredCapabilities": [
      "home_workspace"
    ],
    "isLongTerm": false
  },
  {
    "id": "job.seed-remote",
    "contentStatus": "official",
    "name": "远程校对",
    "description": "按要求检查文字与格式，四小时即可完成一轮。",
    "tags": [
      "work",
      "remote"
    ],
    "kind": "freelance",
    "employmentKind": "repeatable_side_job",
    "hours": 4,
    "basePay": 148,
    "abilityRequired": 16,
    "careerXp": 2,
    "requiredCapabilities": [
      "remote_work"
    ],
    "isLongTerm": false
  },
  {
    "id": "job.operations-specialist",
    "contentStatus": "official",
    "name": "运营专员",
    "description": "负责日常运营与数据跟进，收入进入稳定上升阶段。",
    "tags": [
      "work",
      "office",
      "career"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 248,
    "abilityRequired": 20,
    "reputationRequired": 10,
    "careerXp": 4,
    "experienceTags": ["operations", "office"],
    "experienceRequired": { "operations": 21 },
    "qualificationRequired": ["operations_foundation"],
    "isLongTerm": true
  },
  {
    "id": "job.remote-operator",
    "contentStatus": "official",
    "name": "远程运营助理",
    "description": "在家处理线上业务，工时更短，单位时间收入更高。",
    "tags": [
      "work",
      "remote",
      "career"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 6,
    "basePay": 252,
    "abilityRequired": 22,
    "reputationRequired": 12,
    "careerXp": 4,
    "requiredCapabilities": [
      "remote_work",
      "home_workspace"
    ],
    "isLongTerm": true
  },
  {
    "id": "job.project-coordinator",
    "contentStatus": "official",
    "name": "项目协调员",
    "description": "协调进度和沟通，要求更高，但回报也明显提升。",
    "tags": [
      "work",
      "office",
      "career"
    ],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 318,
    "abilityRequired": 27,
    "reputationRequired": 18,
    "careerXp": 5,
    "isLongTerm": true
  },
  {
    "id": "job.independent-consultant",
    "contentStatus": "official",
    "name": "独立项目顾问",
    "description": "以短项目计费的高阶自由职业，需要能力、声誉和市场判断。",
    "tags": [
      "work",
      "remote",
      "career"
    ],
    "kind": "freelance",
    "employmentKind": "repeatable_side_job",
    "hours": 4,
    "basePay": 268,
    "abilityRequired": 30,
    "reputationRequired": 25,
    "careerXp": 5,
    "requiredCapabilities": [
      "remote_work",
      "market_insight"
    ],
    "isLongTerm": false
  },
  {
    "id": "job.regional-operations-manager",
    "contentStatus": "official",
    "name": "区域运营经理",
    "description": "负责多个门店的经营节奏和团队协作，把运营经验带到更大的范围。",
    "tags": ["work", "management", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 8,
    "basePay": 620,
    "abilityRequired": 52,
    "reputationRequired": 35,
    "careerXp": 7,
    "experienceTags": ["operations", "management"],
    "experienceRequired": { "operations": 61, "management": 1 },
    "qualificationRequired": ["people_management_basics"],
    "category": "management",
    "isLongTerm": true
  },
  {
    "id": "job.category-operations-expert",
    "contentStatus": "official",
    "name": "品类运营专家",
    "description": "不带团队也能走得很远，用专业判断推动商品和运营策略。",
    "tags": ["work", "office", "career", "expert"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 720,
    "abilityRequired": 60,
    "reputationRequired": 28,
    "careerXp": 7,
    "experienceTags": ["operations", "data"],
    "experienceRequired": { "operations": 121 },
    "category": "technical",
    "isLongTerm": true
  },
  {
    "id": "job.photography-assistant-gig",
    "contentStatus": "official",
    "name": "摄影协助 Gig",
    "description": "为一次小型拍摄做现场协助，先把兴趣变成一笔可验证的经验。",
    "tags": ["work", "photography", "gig"],
    "kind": "temporary",
    "employmentKind": "gig",
    "hours": 4,
    "basePay": 168,
    "abilityRequired": 18,
    "reputationRequired": 4,
    "careerXp": 2,
    "experienceTags": ["media"],
    "requiredItems": ["item.vintage-camera"],
    "requirements": { "type": "interest_familiarity_at_least", "tag": "photography", "amount": 2 },
    "isLongTerm": false
  },
  {
    "id": "job.huanliu-warehouse-assistant",
    "contentStatus": "official",
    "name": "环流仓库助理",
    "description": "从收货、分拣和盘点开始，稳定积累物流现场经验。",
    "tags": ["work", "logistics", "starter"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 8,
    "basePay": 136,
    "abilityRequired": 10,
    "reputationRequired": 2,
    "careerXp": 2,
    "experienceTags": ["logistics"],
    "isLongTerm": true
  },
  {
    "id": "job.huanliu-dispatch-coordinator",
    "contentStatus": "official",
    "name": "环流物流协调员",
    "description": "连接仓库、车辆与客户的日常调度，把一线经验变成运营判断。",
    "tags": ["work", "logistics", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 286,
    "abilityRequired": 24,
    "reputationRequired": 12,
    "careerXp": 5,
    "experienceTags": ["logistics", "operations"],
    "experienceRequired": { "logistics": 22 },
    "isLongTerm": true
  },
  {
    "id": "job.course-operations-assistant",
    "contentStatus": "official",
    "name": "课程运营助理",
    "description": "协助课程排期、学员反馈和资料整理，从办公室岗位进入在线教育运营。",
    "tags": ["work", "office", "career", "education"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 238,
    "careerXp": 3,
    "experienceTags": ["office", "operations"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 15 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 12 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.learning-consultant",
    "contentStatus": "official",
    "name": "学习顾问",
    "description": "理解学习需求并陪伴学员完成选择，连接沟通、知识与长期关系。",
    "tags": ["work", "office", "career", "education"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 286,
    "careerXp": 4,
    "experienceTags": ["customer_service", "operations"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 25 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 20 },
      { "type": "attribute_at_least", "attribute": "appearance", "amount": 12 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.course-operations-specialist",
    "contentStatus": "official",
    "name": "课程运营专员",
    "description": "负责课程运营节奏、数据复盘和跨团队协作，把专业判断带进教育产品。",
    "tags": ["work", "office", "career", "education"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 330,
    "careerXp": 5,
    "experienceTags": ["operations", "data", "project"],
    "experienceRequired": { "operations": 21 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 28 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 28 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 22 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.course-teaching-assistant",
    "contentStatus": "official",
    "name": "线上课程助教",
    "description": "协助学员答疑、整理作业与维护课程秩序，把课程资格转成稳定的长期兼职。",
    "tags": ["work", "remote", "education"],
    "kind": "freelance",
    "employmentKind": "repeatable_side_job",
    "hours": 4,
    "basePay": 168,
    "abilityRequired": 14,
    "reputationRequired": 3,
    "careerXp": 2,
    "experienceTags": ["office", "customer_service"],
    "qualificationRequired": ["qualification.workplace-basics"],
    "isLongTerm": false
  },
  {
    "id": "job.research-assistant",
    "contentStatus": "official",
    "name": "研究助理",
    "description": "整理行业资料、核对访谈记录，为客户研究提供可靠的基础。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 275,
    "abilityRequired": 20,
    "reputationRequired": 8,
    "careerXp": 4,
    "experienceTags": ["office", "data"],
    "requiredItems": ["item.seed-laptop"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 26 },
      { "type": "attribute_at_least", "attribute": "professional", "amount": 20 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 15 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.business-analysis-assistant",
    "contentStatus": "official",
    "name": "商业分析助理",
    "description": "把客户问题拆成可验证的数据与假设，开始承担完整分析环节。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 338,
    "abilityRequired": 30,
    "reputationRequired": 12,
    "careerXp": 5,
    "experienceTags": ["office", "data", "project"],
    "experienceRequired": { "office": 40 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 30 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 32 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 20 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.business-analyst",
    "contentStatus": "official",
    "name": "商业分析师",
    "description": "独立完成研究与分析交付，在客户会议中解释判断和建议。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 438,
    "abilityRequired": 42,
    "reputationRequired": 20,
    "careerXp": 6,
    "experienceTags": ["office", "data", "project"],
    "experienceRequired": { "operations": 60 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 42 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 42 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 30 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.travel-product-assistant",
    "contentStatus": "official",
    "name": "旅行产品助理",
    "description": "整理旅行线路、核对活动细节，让一次出发少一些临时决定。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 260,
    "abilityRequired": 18,
    "reputationRequired": 5,
    "careerXp": 4,
    "experienceTags": ["office", "customer_service"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 18 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 15 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.order-operations-assistant",
    "contentStatus": "official",
    "name": "订单运营助理",
    "description": "核对订单、跟进异常，把每天大量的小问题整理成清楚的流程。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 232,
    "abilityRequired": 12,
    "reputationRequired": 2,
    "careerXp": 3,
    "experienceTags": ["office", "operations"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 12 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 12 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.ecommerce-operations-assistant",
    "contentStatus": "official",
    "name": "电商运营助理",
    "description": "协助商品上架、活动配置和数据整理，开始理解一笔订单背后的运营工作。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 272,
    "abilityRequired": 20,
    "reputationRequired": 5,
    "careerXp": 4,
    "experienceTags": ["operations", "data"],
    "experienceRequired": { "operations": 20 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 20 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 18 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 12 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.ecommerce-operations-specialist",
    "contentStatus": "official",
    "name": "电商运营专员",
    "description": "负责一条商品线的活动与复盘，把商品、用户和数据连接起来。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 355,
    "abilityRequired": 32,
    "reputationRequired": 10,
    "careerXp": 5,
    "experienceTags": ["operations", "data", "project"],
    "experienceRequired": { "operations": 40 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 32 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 26 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 20 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.growth-operations",
    "contentStatus": "official",
    "name": "增长运营",
    "description": "围绕拉新、复购和新渠道测试制定增长计划，承担更完整的运营目标。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 445,
    "abilityRequired": 42,
    "reputationRequired": 22,
    "careerXp": 6,
    "experienceTags": ["operations", "data", "project"],
    "experienceRequired": { "operations": 60 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 42 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 36 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 30 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.auto-service-assistant",
    "contentStatus": "official",
    "name": "门店服务助理",
    "description": "协助接待、车辆资料整理和门店日常服务，从汽车服务现场开始积累客户经验。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 145,
    "careerXp": 3,
    "experienceTags": ["customer_service", "office"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 10 },
      { "type": "attribute_at_least", "attribute": "appearance", "amount": 8 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.sales-consultant-assistant",
    "contentStatus": "official",
    "name": "销售顾问助理",
    "description": "协助试驾预约、客户资料和交付准备，把门店服务经验连接到销售协作。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 167,
    "careerXp": 4,
    "experienceTags": ["customer_service", "operations"],
    "experienceRequired": { "customer_service": 20 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 18 },
      { "type": "attribute_at_least", "attribute": "appearance", "amount": 15 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.auto-sales-consultant",
    "contentStatus": "official",
    "name": "汽车销售顾问",
    "description": "理解客户的出行需求并完成车辆建议，稳定的销售奖金通过低频职业事件体现。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 200,
    "careerXp": 5,
    "experienceTags": ["customer_service", "operations"],
    "experienceRequired": { "customer_service": 35 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 32 },
      { "type": "attribute_at_least", "attribute": "appearance", "amount": 28 },
      { "type": "attribute_at_least", "attribute": "network", "amount": 16 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.auto-customer-operations",
    "contentStatus": "official",
    "name": "客户运营专员",
    "description": "维护车主关系、跟进服务反馈并连接门店资源，把销售后的关系做成长期运营。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 220,
    "careerXp": 5,
    "experienceTags": ["customer_service", "operations"],
    "experienceRequired": { "customer_service": 45 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 28 },
      { "type": "attribute_at_least", "attribute": "professional", "amount": 24 },
      { "type": "attribute_at_least", "attribute": "network", "amount": 18 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.production-assistant",
    "contentStatus": "official",
    "name": "制作助理",
    "description": "协助拍摄准备、素材整理和现场沟通，从内容制作的日常节奏开始积累经验。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 153,
    "careerXp": 3,
    "experienceTags": ["media", "office"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 12 },
      { "type": "attribute_at_least", "attribute": "fitness", "amount": 10 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.content-editor",
    "contentStatus": "official",
    "name": "内容编辑",
    "description": "整理内容素材、校对文案并协助形成可发布的内容，连接知识与专业判断。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 200,
    "careerXp": 4,
    "experienceTags": ["media", "office"],
    "experienceRequired": { "media": 20 },
    "requiredItems": ["item.seed-laptop"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 26 },
      { "type": "attribute_at_least", "attribute": "professional", "amount": 20 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.video-operations",
    "contentStatus": "official",
    "name": "视频运营",
    "description": "跟进视频发布、数据反馈和内容迭代，让作品在发布之后继续产生真实反馈。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 232,
    "careerXp": 5,
    "experienceTags": ["media", "operations", "data"],
    "experienceRequired": { "media": 40 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 30 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 26 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 20 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.customer-experience-assistant",
    "contentStatus": "official",
    "name": "客户体验助理",
    "description": "记录用户反馈、协助产品体验和售后跟进，从真实使用场景进入消费科技团队。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 153,
    "careerXp": 3,
    "experienceTags": ["customer_service", "office"],
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "communication", "amount": 12 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 12 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.product-support-specialist",
    "contentStatus": "official",
    "name": "产品支持专员",
    "description": "把设备问题、用户反馈和产品资料整理成可执行的支持方案。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 200,
    "careerXp": 4,
    "experienceTags": ["customer_service", "operations"],
    "experienceRequired": { "customer_service": 20 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 22 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 22 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 18 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.user-research-assistant",
    "contentStatus": "official",
    "name": "用户研究助理",
    "description": "整理访谈记录、观察用户行为并协助验证智能家居产品的真实需求。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 193,
    "careerXp": 4,
    "experienceTags": ["data", "office", "customer_service"],
    "experienceRequired": { "office": 24 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 28 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 24 },
      { "type": "attribute_at_least", "attribute": "professional", "amount": 18 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.lifestyle-product-operations",
    "contentStatus": "official",
    "name": "产品运营",
    "description": "连接产品发布、用户反馈和运营数据，参与消费科技产品的持续迭代。",
    "tags": ["work", "office", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "hours": 7,
    "basePay": 240,
    "careerXp": 5,
    "experienceTags": ["operations", "data", "project"],
    "experienceRequired": { "operations": 42 },
    "requirements": { "type": "all", "conditions": [
      { "type": "attribute_at_least", "attribute": "professional", "amount": 36 },
      { "type": "attribute_at_least", "attribute": "knowledge", "amount": 32 },
      { "type": "attribute_at_least", "attribute": "communication", "amount": 28 },
      { "type": "reputation_at_least", "amount": 18 }
    ] },
    "isLongTerm": true
  },
  {
    "id": "job.city-dispatch-manager",
    "contentStatus": "official",
    "name": "城市配送经理",
    "description": "统筹城市范围内的仓储与配送班次，向区域运营负责人汇报。",
    "tags": ["work", "management", "career", "logistics"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 8,
    "basePay": 545,
    "abilityRequired": 46,
    "reputationRequired": 25,
    "careerXp": 7,
    "experienceTags": ["operations", "logistics", "management"],
    "experienceRequired": { "logistics": 90, "management": 10 }
  },
  {
    "id": "job.learning-product-lead",
    "contentStatus": "official",
    "name": "学习产品负责人",
    "description": "把课程数据与学员反馈转化成学习产品的迭代方向。",
    "tags": ["work", "office", "career", "expert"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 8,
    "basePay": 585,
    "abilityRequired": 48,
    "reputationRequired": 26,
    "careerXp": 7,
    "qualificationRequired": ["data_analysis_foundation"],
    "experienceTags": ["office", "data", "management"],
    "experienceRequired": { "office": 120, "data": 40, "management": 15 }
  },
  {
    "id": "job.principal-analyst",
    "contentStatus": "official",
    "name": "首席分析专家",
    "description": "客户研究结论的最后一道把关人，也负责把分析方法沉淀成团队资产。",
    "tags": ["work", "office", "career", "expert"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 7,
    "basePay": 820,
    "abilityRequired": 62,
    "reputationRequired": 32,
    "careerXp": 8,
    "qualificationRequired": ["data_analysis_foundation"],
    "experienceTags": ["data", "project", "office"],
    "experienceRequired": { "data": 160, "office": 140, "project": 60 }
  },
  {
    "id": "job.travel-experience-designer",
    "contentStatus": "official",
    "name": "资深旅行体验设计师",
    "description": "设计周末短途与长途度假产品，把路线变成可以交付的体验。",
    "tags": ["work", "office", "career", "expert"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 7,
    "basePay": 505,
    "abilityRequired": 44,
    "reputationRequired": 22,
    "careerXp": 6,
    "qualificationRequired": ["project_coordination"],
    "experienceTags": ["project", "media", "customer_service"],
    "experienceRequired": { "project": 70, "customer_service": 60 }
  },
  {
    "id": "job.media-producer-lead",
    "contentStatus": "official",
    "name": "内容监制",
    "description": "把控商业内容的制作标准，协调拍摄、剪辑与客户需求。",
    "tags": ["work", "office", "career", "expert"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 7,
    "basePay": 560,
    "abilityRequired": 49,
    "reputationRequired": 28,
    "careerXp": 7,
    "qualificationRequired": ["media_production_experience"],
    "experienceTags": ["media", "project", "office"],
    "experienceRequired": { "media": 110, "project": 40 }
  },
  {
    "id": "job.lifestyle-product-expert",
    "contentStatus": "official",
    "name": "智能家居产品专家",
    "description": "负责智能家居场景里的核心功能定义与体验打磨。",
    "tags": ["work", "office", "career", "expert"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 7,
    "basePay": 640,
    "abilityRequired": 54,
    "reputationRequired": 24,
    "careerXp": 7,
    "qualificationRequired": ["data_analysis_foundation"],
    "experienceTags": ["office", "data"],
    "experienceRequired": { "office": 100, "data": 80 }
  },
  {
    "id": "job.auto-regional-trainer",
    "contentStatus": "official",
    "name": "区域培训专家",
    "description": "为汽车门店网络设计服务培训，让销售与服务口径保持一致。",
    "tags": ["work", "office", "career", "expert"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 7,
    "basePay": 470,
    "abilityRequired": 41,
    "reputationRequired": 21,
    "careerXp": 6,
    "experienceTags": ["customer_service", "office", "operations"],
    "experienceRequired": { "customer_service": 110, "office": 50 }
  },
  {
    "id": "job.starbridge-growth-director",
    "contentStatus": "official",
    "name": "增长运营总监",
    "description": "对整个电商增长盘子负责，是公司管理层的一员。",
    "tags": ["work", "management", "career"],
    "kind": "regular",
    "employmentKind": "full_time",
    "isLongTerm": true,
    "hours": 8,
    "basePay": 905,
    "abilityRequired": 66,
    "reputationRequired": 40,
    "careerXp": 8,
    "qualificationRequired": ["people_management_basics"],
    "experienceTags": ["operations", "management", "data"],
    "experienceRequired": { "operations": 180, "management": 45, "data": 70 }
  }
] satisfies readonly JobDefinition[];
