import type { RelationshipInteractionDefinition } from '../contracts';

export const officialRelationshipInteractions = [
  {
    id: 'interaction.coffee-with-recruiter',
    contentStatus: 'official',
    name: '和陈宇喝咖啡',
    description: '聊聊最近的工作方向，也听听招聘市场的消息。',
    tags: ['relationship', 'career', 'social'],
    characterId: 'character.chenyu',
    category: 'meal',
    options: [{ id: 'coffee', label: '一起喝咖啡', durationMinutes: 120, cashCost: 100, effects: [{ type: 'relation', characterId: 'character.chenyu', amount: 4 }, { type: 'attribute', attribute: 'mood', amount: 3 }] }],
  },
  {
    id: 'interaction.tech-coffee',
    contentStatus: 'official',
    name: '和徐可聊设备',
    description: '从一杯咖啡开始，交换一些关于远程工作的实际经验。',
    tags: ['relationship', 'technology', 'social'],
    characterId: 'character.xuke',
    category: 'work',
    options: [{ id: 'coffee', label: '聊聊远程工作', durationMinutes: 120, cashCost: 100, effects: [{ type: 'relation', characterId: 'character.xuke', amount: 4 }, { type: 'attribute', attribute: 'knowledge', amount: 1 }] }],
  },
  {
    id: 'interaction.dinner-with-agent',
    contentStatus: 'official',
    name: '和何彦吃饭',
    description: '听房产经纪人讲讲附近的房源和生活变化。',
    tags: ['relationship', 'housing', 'social'],
    characterId: 'character.heyan',
    category: 'meal',
    options: [{ id: 'dinner', label: '一起吃饭', durationMinutes: 180, cashCost: 160, effects: [{ type: 'relation', characterId: 'character.heyan', amount: 5 }, { type: 'attribute', attribute: 'mood', amount: 4 }] }],
  },
  {
    id: 'interaction.business-with-zhou',
    contentStatus: 'official',
    name: '和周妍看看小生意',
    description: '聊聊附近的经营机会，也把生活里的实际问题说清楚。',
    tags: ['relationship', 'business', 'social'],
    characterId: 'character.seed-zhou',
    category: 'business',
    options: [{ id: 'visit', label: '一起看看店', durationMinutes: 180, cashCost: 80, effects: [{ type: 'relation', characterId: 'character.seed-zhou', amount: 7 }, { type: 'attribute', attribute: 'network', amount: 1 }] }],
  },
  {
    id: 'interaction.consulting-review-with-guqing',
    contentStatus: 'official',
    name: '和顾清复盘项目',
    description: '把已经完成的咨询项目重新拆开，看清下一次客户合作可以怎样推进。',
    tags: ['relationship', 'career', 'business'],
    characterId: 'character.guqing',
    category: 'work',
    options: [{ id: 'review', label: '一起复盘项目', durationMinutes: 120, cashCost: 120, effects: [{ type: 'relation', characterId: 'character.guqing', amount: 5 }, { type: 'attribute', attribute: 'professional', amount: 1 }] }],
  },
  {
    id: 'interaction.bookstore-with-lin',
    contentStatus: 'official',
    name: '和林晨逛书店',
    description: '在书架间聊聊最近读到的东西，给关系留一点不带任务的时间。',
    tags: ['relationship', 'culture', 'social'],
    characterId: 'character.seed-lin',
    category: 'outing',
    options: [{ id: 'browse', label: '一起逛书店', durationMinutes: 120, cashCost: 90, effects: [{ type: 'relation', characterId: 'character.seed-lin', amount: 4 }, { type: 'attribute', attribute: 'knowledge', amount: 1 }] }],
  },
  {
    id: 'interaction.song-yuran-gallery',
    contentStatus: 'official',
    name: '陪宋雨然看插画小展',
    description: '去旧城的小展馆看看这一季的新插画，也看看她的新稿。',
    tags: ['social'],
    characterId: 'character.song-yuran',
    category: 'outing',
    options: [{ id: 'stroll', label: '一起看展漫步', durationMinutes: 120, cashCost: 40, effects: [{ type: 'relation', characterId: 'character.song-yuran', amount: 5 }, { type: 'attribute', attribute: 'appearance', amount: 1 }] }],
  },
  {
    id: 'interaction.tang-ke-meal',
    contentStatus: 'official',
    name: '和唐柯吃增肌餐',
    description: '训练结束后的那顿饭，唐柯对食材比例的坚持令人佩服。',
    tags: ['social'],
    characterId: 'character.tang-ke',
    category: 'meal',
    options: [{ id: 'bowl', label: '一起吃健康餐盘', durationMinutes: 60, cashCost: 45, effects: [{ type: 'relation', characterId: 'character.tang-ke', amount: 4 }, { type: 'stat', stat: 'ability', amount: 1 }] }],
  },
  {
    id: 'interaction.luo-lan-nighttalk',
    contentStatus: 'official',
    name: '听罗岚聊书',
    description: '打烊后的书店里，罗岚总会翻出一本冷门又好看的书。',
    tags: ['social'],
    characterId: 'character.luo-lan',
    category: 'work',
    options: [{ id: 'night', label: '书店夜谈选书', durationMinutes: 120, cashCost: 20, effects: [{ type: 'relation', characterId: 'character.luo-lan', amount: 5 }, { type: 'attribute', attribute: 'knowledge', amount: 1 }] }],
  },
  {
    id: 'interaction.yan-zhe-late-meal',
    contentStatus: 'official',
    name: '和严哲赶一场夜宵',
    description: '严哲出差回来的深夜，总有一家还亮着灯的馆子值得坐下。',
    tags: ['social'],
    characterId: 'character.yan-zhe',
    category: 'meal',
    options: [{ id: 'late', label: '深夜商务简餐', durationMinutes: 120, cashCost: 60, effects: [{ type: 'relation', characterId: 'character.yan-zhe', amount: 4 }, { type: 'attribute', attribute: 'network', amount: 1 }] }],
  },
] satisfies readonly RelationshipInteractionDefinition[];
